# Generated by Django 4.2.2 on 2023-07-23 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(max_length=30, unique=True, verbose_name='Telegram ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bot user',
                'verbose_name_plural': 'Bot users',
                'db_table': 'bot_users',
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(unique=True)),
            ],
            options={
                'verbose_name': 'Season',
                'verbose_name_plural': 'Seasons',
                'db_table': 'seasons',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number')),
                ('first_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='First name')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=6, null=True, verbose_name='Gender')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Birth date')),
                ('birth_country', models.CharField(blank=True, max_length=150, null=True, verbose_name='Birth country')),
                ('birth_city', models.CharField(blank=True, max_length=150, null=True, verbose_name='Birth city')),
                ('nationality', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nationality')),
                ('passport_number', models.CharField(blank=True, max_length=150, null=True, verbose_name='Passport number')),
                ('passport_exp_date', models.DateField(blank=True, null=True, verbose_name='Passport expiration date')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorces', 'Divorced'), ('widowed', 'Widowed')], max_length=10, null=True, verbose_name='Marital status')),
                ('children_count', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Children count')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bot_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.botuser', verbose_name='Bot user')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.season', verbose_name='Season')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'db_table': 'applications',
                'unique_together': {('bot_user', 'season')},
            },
        ),
    ]
