# Generated by Django 4.2.2 on 2023-07-25 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='full_name',
            field=models.CharField(default='', max_length=255, verbose_name='Full name'),
            preserve_default=False,
        ),
    ]
